name: Trigger auto deployment for tmtest-bugbash-centralus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tmtest-bugbash-centralus-AutoDeployTrigger-a1838f04-4494-4661-b244-ddacb78ab230.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTBUGBASHCENTRALUS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTBUGBASHCENTRALUS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTBUGBASHCENTRALUS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TMTESTBUGBASHCENTRALUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTBUGBASHCENTRALUS_REGISTRY_PASSWORD }}
          containerAppName: tmtest-bugbash-centralus
          resourceGroup: tm-test-new-1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


